/* 01 */


package exception_handling;


public class ExceptionDemo {
    
    public static void main(String[] args) {
       
        try{
        
        int x =10;
        int y =0;
        int result = x/y ;
        System.out.println(result);
            
        }catch(ArrayIndexOutOfBoundsException e1)
        {
            System.out.println("Exception 1 : "+e1);
        }

     
        catch(Exception e2)
        {
            System.out.println("Exception 2 : "+e2);
        }
        finally 
        {
            System.out.println("Last line of the program ");
        }
        
        
    }
}



/* 02 */



package exception_handling;


public class ExceptionDemo2 {
    
    public static void main(String[] args) {
       
        try{
        
        int[] a = new int[4];
        a[4]=10 ;
            
        }catch(ArithmeticException e1)
        {
            System.out.println("Exception 1 : "+e1);
        }

     
        catch(ArrayIndexOutOfBoundsException e2)
        {
            System.out.println("Exception 2 : "+e2);
        }
        finally 
        {
            System.out.println("Last line of the program ");
        }
        
        
    }
}
